[package]
name = "hypha-messages"
version.workspace = true
publish.workspace = true
edition.workspace = true
license = "Apache-2.0"

[dependencies]
libp2p.workspace = true
serde.workspace = true
uuid.workspace = true
hypha-network.workspace = true
hypha-resources.workspace = true
