[package]
name = "hypha-leases"
version.workspace = true
publish.workspace = true
edition.workspace = true
license = "Apache-2.0"

[dependencies]
thiserror.workspace = true
tokio.workspace = true
tracing.workspace = true
uuid.workspace = true
